# Generated by Django 4.2.1 on 2023-05-27 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_title', models.CharField(max_length=200)),
                ('question', models.TextField(max_length=1000)),
                ('assign_file', models.FileField(default=None, max_length=250, null=True, upload_to='question/')),
                ('created', models.DateField(editable=False, null=True)),
                ('deadline', models.DateField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.course')),
                ('fac_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty', to='main.faculty')),
            ],
            options={
                'verbose_name_plural': 'Assignments',
            },
        ),
    ]
