# Generated by Django 4.2.1 on 2023-05-28 06:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('Assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='id',
        ),
        migrations.AddField(
            model_name='assignments',
            name='assign_number',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='main.course'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignments',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(default=None, max_length=250, null=True, upload_to='submissions/')),
                ('submitted_time', models.DateTimeField(auto_now_add=True)),
                ('submission_status', models.CharField(max_length=20)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assg_number', to='Assignments.assignments')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.course')),
                ('fac_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fac', to='main.faculty')),
                ('student_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='main.student')),
            ],
            options={
                'verbose_name_plural': 'Assignments',
            },
        ),
    ]
