# Generated by Django 4.2.1 on 2023-05-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0004_alter_assignments_assign_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assign_file',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='media/question/'),
        ),
    ]
