# Generated by Django 4.2.1 on 2023-05-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0005_alter_assignments_assign_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assign_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='question/'),
        ),
    ]
