# Generated by Django 4.2.1 on 2023-06-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0007_rename_assign_file_assignments_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submission_status',
        ),
    ]
