# Generated by Django 4.2.1 on 2023-06-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('material_number', models.IntegerField(primary_key=True, serialize=False)),
                ('material_title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='question/')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Courses', to='main.course')),
                ('faculty_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Faculty', to='main.faculty')),
            ],
            options={
                'verbose_name_plural': 'Course Material',
            },
        ),
    ]
